0000000000000000000000GRANT EXECUTE ON threeReleaseUpgradeBlendedDiscountCaseLock TO b4nuser
GO
GRANT EXECUTE ON threeReleaseUpgradeBlendedDiscountCaseLock TO ofsuser
GO
GRANT EXECUTE ON threeReleaseUpgradeBlendedDiscountCaseLock TO reportuser
GO
