000000000000000000000000GRANT EXECUTE ON FindStringInSP TO b4nuser
GO
GRANT EXECUTE ON FindStringInSP TO helpdesk
GO
GRANT EXECUTE ON FindStringInSP TO ofsuser
GO
GRANT EXECUTE ON FindStringInSP TO reportuser
GO
GRANT EXECUTE ON FindStringInSP TO b4nexcel
GO
GRANT EXECUTE ON FindStringInSP TO b4nloader
GO
