0000000000000GRANT EXECUTE ON h3giGetVATRate TO b4nuser
GO
GRANT EXECUTE ON h3giGetVATRate TO helpdesk
GO
GRANT EXECUTE ON h3giGetVATRate TO ofsuser
GO
GRANT EXECUTE ON h3giGetVATRate TO reportuser
GO
GRANT EXECUTE ON h3giGetVATRate TO b4nexcel
GO
GRANT EXECUTE ON h3giGetVATRate TO b4nloader
GO
